services:
  dev:
    platform: "linux/amd64"
    image: cr.pointcaster.net/pointcaster-dev:latest-linux
    command: fish
    stdin_open: true
    tty: true
    working_dir: /pointcaster
    volumes:
      - .:/pointcaster
  dev-win:
    platform: "windows/amd64"
    image: cr.pointcaster.net/pointcaster-dev:latest-windows
    command: powershell
    stdin_open: true
    tty: true
    working_dir: C:\pointcaster
    isolation: process
    volumes:
      - .:C:\pointcaster
